/*
 * Stellar Test Anchor
 *
 * An implementation of a SEP compliant Stellar Anchor
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

type AuthToken struct {
	Token string `json:"token"`
}
