/*
 * Stellar Test Anchor
 *
 * An implementation of a SEP compliant Stellar Anchor
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ChallengeTransaction struct {
	Transaction string `json:"transaction"`
}
